modLoader="javafml"
loaderVersion="[35,)"
license="The Unlicense"

[[mods]]
modId="cultivation"
version="${file.jarVersion}"
displayName="Cultivation Mod"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="examplemod.png"
#credits="Thanks for this example mod goes to Java" #optional
#authors="Love, Cheese and small house plants" #optional
description="A wuxia-style cultivation mod, made for cs class final project"

[[dependencies.cultivation]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cultivation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
